package httputils

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
)

//AutoGenerated 接受返回的数据
type AutoGenerated struct {
	Status int `json:"status"`
	Data   struct {
		List []struct {
			Time         string  `json:"time"`
			Citycode     string  `json:"citycode"`
			Cityname     string  `json:"cityname"`
			Index        string  `json:"index"`
			LastIndex    string  `json:"last_index"`
			IndexLevel   int     `json:"index_level"`
			Speed        string  `json:"speed"`
			CityCoords   string  `json:"city_coords"`
			Provincecode int     `json:"provincecode"`
			Provincename string  `json:"provincename"`
			WeekRate     float64 `json:"weekRate"`
		} `json:"list"`
		Datetime string `json:"datetime"`
	} `json:"data"`
	Message interface{} `json:"message"`
}

//HTTPGet 网络的get请求
func HTTPGet(url string) {
	resp, err := http.Get(url)
	if err != nil {
		// handle error
	}
	defer resp.Body.Close()
	body, err := ioutil.ReadAll(resp.Body)

	if err != nil {
		// handle error
	}

	fmt.Println(string(body))
	mydata := AutoGenerated{}
	json.Unmarshal(body, &mydata)
	fmt.Printf("%v\n", mydata)
}
